// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoSalWWkrTkdO3ijv8SZP8IQLAzyA445k',
    appId: '1:1034973894608:web:56335fd98b127691754bd5',
    messagingSenderId: '1034973894608',
    projectId: 'massage-ad829',
    authDomain: 'massage-ad829.firebaseapp.com',
    storageBucket: 'massage-ad829.appspot.com',
    measurementId: 'G-EG1CEWL9YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSMktCwlQFOKl55z8LE9_ZuJwzxOBmowI',
    appId: '1:1034973894608:android:5ec985aec19af4ce754bd5',
    messagingSenderId: '1034973894608',
    projectId: 'massage-ad829',
    storageBucket: 'massage-ad829.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEDv_y-f57fmG95XOiVzQOuJ5HBzXbr9I',
    appId: '1:1034973894608:ios:940180833ee13d68754bd5',
    messagingSenderId: '1034973894608',
    projectId: 'massage-ad829',
    storageBucket: 'massage-ad829.appspot.com',
    iosBundleId: 'com.example.massage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEDv_y-f57fmG95XOiVzQOuJ5HBzXbr9I',
    appId: '1:1034973894608:ios:940180833ee13d68754bd5',
    messagingSenderId: '1034973894608',
    projectId: 'massage-ad829',
    storageBucket: 'massage-ad829.appspot.com',
    iosBundleId: 'com.example.massage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoSalWWkrTkdO3ijv8SZP8IQLAzyA445k',
    appId: '1:1034973894608:web:34989b695ea26b5f754bd5',
    messagingSenderId: '1034973894608',
    projectId: 'massage-ad829',
    authDomain: 'massage-ad829.firebaseapp.com',
    storageBucket: 'massage-ad829.appspot.com',
    measurementId: 'G-R72FG6PELS',
  );
}
